image: fpco/stack-build:latest
stages:
  - build

build-latest:
  stage: build
  cache:
    paths:
      - .stack-root
    key: ${CI_COMMIT_REF_SLUG}-11
  script:
    - stack --stack-root ${PWD}/.stack-root --install-ghc build --test

build-9:
  stage: build
  cache:
    paths:
      - .stack-root
    key: ${CI_COMMIT_REF_SLUG}-9
  script:
    - stack --stack-root ${PWD}/.stack-root --stack-yaml stack-9.yaml --install-ghc build --test
